projects:
  default:
    schema:
      - "./storefront/schema.graphql"
      - "./storefront/$houdini/graphql/schema.graphql"
    documents:
      - "./storefront/**/*.gql"
      - "./storefront/$houdini/graphql/documents.gql"
